Sergiy M.Test task
White-Digital-Company/react-native-test-task-app pull request #3
Opened 2024-11-01 13:00 UTC by Serhio15210

2024-11-01 13:44 UTC, chromakeeey requested changes
ще недоліки:
- в assets краще розподіляти по папочкам різні типи файлів, до прикладу
assets/images
assets/icons
assets/fonts

- потрібно встановити prettier і eslint, гарно відформатувати код
- використати для tailwind бібліотеку: https://www.npmjs.com/package/twrnc
- також УВАЖНО читати документації до бібліотек, тому що багато помилок по структурі

2024-11-01 13:44 UTC, chromakeeey commented on App.tsx
> +import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
потрібно додати блоки між логічними блоками коду

2024-11-01 13:44 UTC, chromakeeey commented on App.tsx
> +export const queryClient = new QueryClient()
як і тут, потрібен додатковий пробіл

2024-11-01 13:44 UTC, chromakeeey commented on App.tsx
> +    <QueryClientProvider client={queryClient}>
немає стилю коду, тут потрібні ще одна табуляція, рекомендую встановити eslint та prettier для vscode

2024-11-01 13:44 UTC, chromakeeey commented on babel.config.js
> +          "@": "./src",
якщо це зроблено для абсолютних шляхів, давай краще це робити через tsconfig

2024-11-01 13:44 UTC, chromakeeey commented on src/api/index.ts
> +const axios=useAxios()
тут груба помилка, в тебе є "хук" useAxios який назвою визначає себе як хук, але це ж взагалі не хук
для того щоб задати baseUrl ми використовуємо `axios.create({ ... })`

2024-11-01 13:44 UTC, chromakeeey commented on src/api/index.ts
> +export const getActivities=async () => {
тут так само, немає стилю коду, все виглядає необережно

2024-11-01 13:44 UTC, chromakeeey commented on src/api/index.ts
> +  return response?.data
response?.data, хіба response може бути undefined?

2024-11-01 13:44 UTC, chromakeeey commented on src/api/queries/index.ts
> +export const getActivitiesQuery = () => {
в великому застосунку коли в тебе буде багато модулів, які звʼязані з API, то зберігати все в одному файлі не підійде, потрібно це буде логічно розподіляти, як на мене оптимальна структура наступна:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/6f409b43-c9cc-4c8c-a8d8-b0f21b6d19c7">

actions -> зберігаються axios функції
constants -> query keys
useActivities -> твій useQuery хук
useActivitiesMutations -> mutations

2024-11-01 13:44 UTC, chromakeeey commented on src/components/activity-card/index.tsx
> +      <View className="bg-[#F7F7F7] rounded-2xl p-5" style={{ gap: 6 }}>
кольори мають зберігатись в конфігах tailwind

2024-11-01 13:44 UTC, chromakeeey commented on src/components/custom-button/index.tsx
> +type CustomButtonProps = {
використовуємо interface замість type,
type в основному використовуємо для `type TransportType = 'bus' | 'car' | 'plane'`

2024-11-01 13:44 UTC, chromakeeey commented on src/components/activity-card/index.tsx
> +  const getImg = useCallback(async () => {
не потрібно цього робити, просто `<Image source={{ uri: imageUrl }} />`

2024-11-01 13:44 UTC, chromakeeey commented on src/components/custom-button/index.tsx
> +  const width = Dimensions.get("window").width;
давай використаємо бібліотеку react-native-responsive-screen

2024-11-01 13:44 UTC, chromakeeey commented on src/screens/ActivityScreen.tsx
> +const ActivityScreen = ({ route }: any) => {
типізації взагалі нема

2024-11-01 13:44 UTC, chromakeeey commented on src/screens/RootRouter.tsx
> +const LeftButton = (props) => {
це має бути в окрему файлі

2024-11-01 13:44 UTC, chromakeeey commented on src/screens/RootRouter.tsx
> +const LeftButton = (props) => {
типізації теж нема

2024-11-01 13:44 UTC, chromakeeey commented on src/components/activity-card/index.tsx
> +  const navigation = useNavigation();
ми не можемо використовувати тут useNavigation, тільки на екранах

2024-11-01 13:44 UTC, chromakeeey commented on src/screens/ActivityScreen.tsx
> +const ActivityScreen = ({ route }: any) => {
якщо вже використано useNavigation, чому useRoute неможливо? і потрібно типізацію до useRoute

2024-11-01 13:44 UTC, chromakeeey commented on src/screens/HomeScreen.tsx
> +      <FlatList contentContainerStyle={{ padding: 20, gap: 10 }} showsVerticalScrollIndicator={false} data={activities}
списки потрібно винести в окремий компонент

2024-11-04 14:45 UTC, chromakeeey requested changes

2024-11-04 14:45 UTC, chromakeeey commented on App.tsx
> +import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
тут не має пробілу, не має стиля коду, якого хотіли б бачити, я залишу коммент лиш про цей момент, але в коді їх багато, потрібно буде пройтись по всім моментам і виправити

2024-11-04 14:45 UTC, chromakeeey commented on App.tsx
> +export const queryClient = new QueryClient()
давай створимо queryClient в @api/queryClient

2024-11-04 14:45 UTC, chromakeeey commented on babel.config.js
>            '@/screens': './src/screens',
абсолютні шляхи мають бути в tsconfig.json, я вже лишав на це коментар
+ вони виглядають не дуже обережно
```
@/components -> @components
@/api -> @api
```

2024-11-04 14:45 UTC, chromakeeey commented on babel.config.js
> +          '#/icons': './assets/icons',
не потрібні абсолютні шляхи на images, fonts, тільки на assets/

2024-11-04 14:45 UTC, chromakeeey commented on declarations.d.ts
> +declare module '*.svg' {
тут не має бути any

2024-11-04 14:45 UTC, chromakeeey commented on src/api/api.ts
> +  headers: {
цей header тут не потрібен

2024-11-04 14:45 UTC, chromakeeey commented on src/api/api.ts
> +export const api = axios.create({
`api -> httpClient`

2024-11-04 14:45 UTC, chromakeeey commented on src/api/resources/activities/constants.ts
> +export const queryIds = {
я вже писав про структуру папок для api, прикріпляв скріни, як це має виглядати, це не було зроблено

2024-11-04 14:45 UTC, chromakeeey commented on src/api/resources/activities/queries/index.ts
> +export const useActivitiesQuery = () => {
```
const query = useQuery({
 ...
})

return query
```

2024-11-04 14:45 UTC, chromakeeey commented on src/components/activity-card/index.tsx
> +    <>
чому це обертається в пустий тег?

2024-11-04 14:45 UTC, chromakeeey commented on src/screens/ActivityScreen.tsx
> +type ActivityRouteProp = RouteProp<RootStackParamList, 'Activity'>
це не має бути на екрані, плюс існує універсальний тип, 

![image](https://github.com/user-attachments/assets/ebce5e6d-7d40-46c9-b257-43760863b44e)
https://reactnavigation.org/docs/typescript/#type-checking-the-navigator

2024-11-04 14:45 UTC, chromakeeey commented on src/screens/HomeScreen.tsx
> +const HomeScreen = ({ navigation }: RootStackScreenProps<'Home'>) => {
чомусь десь useRoute, десь navigation витягуєш з props, потрібно використовувати лиш хуки useRoute, useNavigation

2024-11-04 14:45 UTC, chromakeeey commented on src/screens/HomeScreen.tsx
> +  const { activities, isActivitiesLoading } = useActivities()
тут не потрібно робити деструктуризацію

2024-11-04 14:45 UTC, chromakeeey commented on tailwind.config.js
> +        mainBorder: '#F5F5F5',
файл конфігу так не потрібно формувати, потрібно 

black: '#000'
white: '#fff'

ми не підвʼязуємо кольори до певних компонентів, а до справжніх кольорів

2024-11-04 17:24 UTC, Serhio15210 commented on babel.config.js
>            '@/screens': './src/screens',
тобто і в babel.config також змінити @/components -> @components і тд? Без абсолютних шляхів у babel.config будуть помилки

2024-11-04 17:28 UTC, Serhio15210 commented on App.tsx
> +import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
це коментар до останнього коміту? Я наче виправляв, пробілів не було

2025-09-23 14:30 UTC, closed without merging